import type { Agent } from "./types";

export const DEFAULT_AGENTS: Agent[] = [
  {
    id: "zara",
    name: "Zara",
    tag: "[REV]",
    title: "Revenue Strategist",
    color: "#FE0000",
    status: "idle",
    room: "Sales Floor",
    description:
      "Analyzes revenue streams, detects pricing anomalies, and forecasts growth targets using transaction data.",
    quickActions: ["/analyze revenue", "/predict revenue", "/ask zara top products"],
  },
  {
    id: "kofi",
    name: "Kofi",
    tag: "[OPS]",
    title: "Operations Commander",
    color: "#FE0000",
    status: "idle",
    room: "Ops Center",
    description: "Monitors workflow efficiency and automates routine logistical tasks across departments.",
    quickActions: ["/analyze operations", "/automate operations", "/ask kofi bottlenecks"],
  },
  {
    id: "amara",
    name: "Amara",
    tag: "[CUS]",
    title: "Customer Champion",
    color: "#FE0000",
    status: "idle",
    room: "CX Lounge",
    description: "Segments customer bases and identifies churn patterns through behavioral analysis.",
    quickActions: ["/analyze customers", "/predict churn", "/ask amara top customers"],
  },
  {
    id: "idris",
    name: "Idris",
    tag: "[INV]",
    title: "Inventory Guardian",
    color: "#FE0000",
    status: "idle",
    room: "Warehouse",
    description: "Monitors stock levels and automates reorder alerts to prevent shortages.",
    quickActions: ["/analyze inventory", "/predict inventory", "/ask idris reorder"],
  },
  {
    id: "nala",
    name: "Nala",
    tag: "[MKT]",
    title: "Marketing Maven",
    color: "#FE0000",
    status: "idle",
    room: "Creative Lab",
    description: "Tracks campaign ROI and optimizes social media engagement strategies.",
    quickActions: ["/create campaign", "/design social post", "/analyze marketing"],
  },
  {
    id: "tariq",
    name: "Tariq",
    tag: "[FIN]",
    title: "Finance Wizard",
    color: "#FE0000",
    status: "idle",
    room: "Finance Vault",
    description: "Forecasts cash flow and prepares detailed financial reporting for stakeholders.",
    quickActions: ["/analyze finance", "/predict cashflow", "/ask tariq tax report"],
  },
  {
    id: "sana",
    name: "Sana",
    tag: "[DAT]",
    title: "Data Scientist",
    color: "#FE0000",
    status: "idle",
    room: "Analytics Bay",
    description: "Aggregates market trends and competitor data into actionable intelligence.",
    quickActions: ["/research trends", "/research competitors", "/analyze data"],
  },
  {
    id: "ravi",
    name: "Ravi",
    tag: "[TEC]",
    title: "Tech Architect",
    color: "#FE0000",
    status: "idle",
    room: "Server Room",
    description: "Develops automation scripts and manages the underlying platform infrastructure.",
    quickActions: ["/create code", "/automate api", "/analyze system"],
  },
  {
    id: "luna",
    name: "Luna",
    tag: "[GRO]",
    title: "Growth Hacker",
    color: "#FE0000",
    status: "idle",
    room: "Growth Lab",
    description:
      "Identifies growth opportunities and optimizes conversion funnels through experimentation.",
    quickActions: ["/analyze growth", "/create experiment", "/predict growth"],
  },
  {
    id: "omar",
    name: "Omar",
    tag: "[PAR]",
    title: "Partnership Connector",
    color: "#FE0000",
    status: "idle",
    room: "Deal Room",
    description: "Manages B2B relationships and generates essential business documentation.",
    quickActions: ["/create business-plan", "/create pitch-deck", "/research partners"],
  },
];

export const ANALYZE_MAP: Record<string, string> = {
  revenue: "zara",
  operations: "kofi",
  customers: "amara",
  inventory: "idris",
  marketing: "nala",
  finance: "tariq",
  data: "sana",
  system: "ravi",
  growth: "luna",
};
export const PREDICT_MAP: Record<string, string> = {
  revenue: "zara",
  churn: "amara",
  inventory: "idris",
  cashflow: "tariq",
  growth: "luna",
};
export const CREATE_MAP: Record<string, string> = {
  campaign: "nala",
  code: "ravi",
  experiment: "luna",
  "business-plan": "omar",
  "pitch-deck": "omar",
  report: "sana",
  sop: "omar",
};
