# -*- coding: utf-8 -*-
"""
Mafalia × Graphify Integration
================================
Turns the Mafalia data directory (CSVs, code, docs) into a queryable
knowledge graph using graphifyy.  Agents can then query the graph for
structural insights, surprising connections, and cross-domain patterns.

The graph is persistent: first build takes time, subsequent queries are
instant and cost zero tokens.
"""

import os
import json
import subprocess
import shutil
from pathlib import Path
from typing import Any, Dict, List, Optional
from datetime import datetime

# Optional: use the graphify Python API if available, otherwise CLI
try:
    import networkx as nx
    HAS_NETWORKX = True
except ImportError:
    HAS_NETWORKX = False


class MafaliaGraphify:
    """
    Wraps graphifyy to build and query a knowledge graph of the Mafalia
    business data, agent code, and documentation.
    """

    def __init__(self, data_dir: str = ".", output_dir: str = ""):
        self.data_dir = Path(data_dir).resolve()
        self.output_dir = Path(output_dir) if output_dir else self.data_dir / "graphify-out"
        self.graph_json = self.output_dir / "graph.json"
        self.report_md = self.output_dir / "GRAPH_REPORT.md"
        self.graph_html = self.output_dir / "graph.html"
        self._graph: Optional[Any] = None

    # ── Build ────────────────────────────────────────────────────────

    def build(self, mode: str = "default", update: bool = False) -> Dict:
        """
        Build or update the knowledge graph from the data directory.
        
        Args:
            mode: "default" or "deep" (more aggressive inference)
            update: If True, only re-extract changed files
            
        Returns:
            Status dict with paths and stats
        """
        graphify_bin = shutil.which("graphify")
        if not graphify_bin:
            return {
                "error": "graphifyy not installed. Run: pip install graphifyy && graphify install",
                "install_cmd": "pip install graphifyy && graphify install"
            }

        cmd = [graphify_bin, str(self.data_dir)]

        if mode == "deep":
            cmd.extend(["--mode", "deep"])
        if update:
            cmd.append("--update")

        # Build wiki for agent-crawlable output
        cmd.append("--wiki")

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=300,  # 5 minute timeout
                cwd=str(self.data_dir),
            )

            if result.returncode != 0:
                return {
                    "error": f"graphify failed: {result.stderr[:500]}",
                    "returncode": result.returncode,
                }

            stats = self._get_graph_stats()
            return {
                "success": True,
                "graph_json": str(self.graph_json),
                "report_md": str(self.report_md),
                "graph_html": str(self.graph_html),
                "output_dir": str(self.output_dir),
                "stats": stats,
                "stdout": result.stdout[:1000],
            }
        except subprocess.TimeoutExpired:
            return {"error": "graphify timed out (5 min limit)"}
        except Exception as e:
            return {"error": str(e)}

    def build_from_csvs(self) -> Dict:
        """
        Build a graph specifically from CSV files in the data directory.
        Creates a temporary .graphifyignore to focus only on CSVs and docs.
        """
        ignore_path = self.data_dir / ".graphifyignore"
        had_ignore = ignore_path.exists()
        old_content = ""

        if had_ignore:
            old_content = ignore_path.read_text()

        try:
            # Focus on CSVs, markdown, and Python agent code
            ignore_path.write_text(
                "# Auto-generated by Mafalia for CSV-focused graph\n"
                "node_modules/\n"
                "dist/\n"
                "release/\n"
                ".git/\n"
                "__pycache__/\n"
                "*.lock\n"
                "*.exe\n"
            )
            return self.build()
        finally:
            # Restore original .graphifyignore
            if had_ignore:
                ignore_path.write_text(old_content)
            elif ignore_path.exists():
                ignore_path.unlink()

    # ── Query ────────────────────────────────────────────────────────

    def query(self, question: str, budget: int = 2000, dfs: bool = False) -> Dict:
        """
        Query the knowledge graph with a natural language question.
        
        Args:
            question: Natural language question
            budget: Max tokens for response
            dfs: If True, trace a specific path (depth-first)
            
        Returns:
            Query results dict
        """
        # Try CLI query first
        graphify_bin = shutil.which("graphify")
        if graphify_bin and self.graph_json.exists():
            cmd = [
                graphify_bin, "query", question,
                "--graph", str(self.graph_json),
                "--budget", str(budget),
            ]
            if dfs:
                cmd.append("--dfs")

            try:
                result = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=60,
                )
                return {
                    "answer": result.stdout.strip(),
                    "question": question,
                    "graph_path": str(self.graph_json),
                }
            except Exception as e:
                return {"error": str(e), "question": question}

        # Fallback: query the graph.json directly with NetworkX
        if HAS_NETWORKX and self.graph_json.exists():
            return self._query_local(question)

        return {
            "error": "No graph found. Run /graphify-build first.",
            "question": question,
        }

    def explain(self, concept: str) -> Dict:
        """Explain a specific concept/node in the graph."""
        graphify_bin = shutil.which("graphify")
        if graphify_bin and self.graph_json.exists():
            try:
                result = subprocess.run(
                    [graphify_bin, "explain", concept, "--graph", str(self.graph_json)],
                    capture_output=True, text=True, timeout=60,
                )
                return {"explanation": result.stdout.strip(), "concept": concept}
            except Exception as e:
                return {"error": str(e)}

        # Fallback: search local graph
        if HAS_NETWORKX and self.graph_json.exists():
            return self._explain_local(concept)

        return {"error": "No graph found. Run /graphify-build first."}

    def find_path(self, source: str, target: str) -> Dict:
        """Find the relationship path between two concepts."""
        graphify_bin = shutil.which("graphify")
        if graphify_bin and self.graph_json.exists():
            try:
                result = subprocess.run(
                    [graphify_bin, "path", source, target, "--graph", str(self.graph_json)],
                    capture_output=True, text=True, timeout=60,
                )
                return {"path": result.stdout.strip(), "source": source, "target": target}
            except Exception as e:
                return {"error": str(e)}
        return {"error": "No graph found. Run /graphify-build first."}

    # ── Report ───────────────────────────────────────────────────────

    def get_report(self) -> Dict:
        """Get the GRAPH_REPORT.md contents - god nodes, surprising connections, etc."""
        if self.report_md.exists():
            content = self.report_md.read_text(encoding="utf-8", errors="replace")
            return {
                "report": content,
                "path": str(self.report_md),
                "size": self.report_md.stat().st_size,
            }
        return {"error": "No report found. Run /graphify-build first."}

    def get_html_path(self) -> Optional[str]:
        """Get path to the interactive graph HTML visualization."""
        if self.graph_html.exists():
            return str(self.graph_html)
        return None

    # ── Stats & Inspection ───────────────────────────────────────────

    def _get_graph_stats(self) -> Dict:
        """Extract stats from the graph.json."""
        if not self.graph_json.exists():
            return {}
        try:
            data = json.loads(self.graph_json.read_text(encoding="utf-8"))
            nodes = data.get("nodes", [])
            edges = data.get("edges", data.get("links", []))
            
            # Count by type
            node_types: Dict[str, int] = {}
            for n in nodes:
                t = n.get("type", "unknown")
                node_types[t] = node_types.get(t, 0) + 1

            edge_types: Dict[str, int] = {}
            for e in edges:
                t = e.get("type", e.get("relationship", "unknown"))
                edge_types[t] = edge_types.get(t, 0) + 1

            return {
                "total_nodes": len(nodes),
                "total_edges": len(edges),
                "node_types": node_types,
                "edge_types": edge_types,
                "communities": len(set(n.get("community", 0) for n in nodes)),
            }
        except Exception as e:
            return {"error": str(e)}

    def is_built(self) -> bool:
        """Check if the graph has already been built."""
        return self.graph_json.exists()

    def graph_age(self) -> Optional[str]:
        """How old is the current graph?"""
        if self.graph_json.exists():
            mtime = datetime.fromtimestamp(self.graph_json.stat().st_mtime)
            delta = datetime.now() - mtime
            if delta.days > 0:
                return f"{delta.days} days ago"
            hours = delta.seconds // 3600
            if hours > 0:
                return f"{hours} hours ago"
            return f"{delta.seconds // 60} minutes ago"
        return None

    # ── Local Graph Queries (NetworkX fallback) ──────────────────────

    def _load_graph(self):
        """Load graph.json into a NetworkX graph."""
        if self._graph is not None:
            return self._graph

        if not HAS_NETWORKX or not self.graph_json.exists():
            return None

        data = json.loads(self.graph_json.read_text(encoding="utf-8"))
        G = nx.Graph()

        for node in data.get("nodes", []):
            nid = node.get("id", node.get("name", ""))
            G.add_node(nid, **{k: v for k, v in node.items() if k != "id"})

        for edge in data.get("edges", data.get("links", [])):
            src = edge.get("source", edge.get("from", ""))
            tgt = edge.get("target", edge.get("to", ""))
            G.add_edge(src, tgt, **{k: v for k, v in edge.items() if k not in ("source", "target", "from", "to")})

        self._graph = G
        return G

    def _query_local(self, question: str) -> Dict:
        """Search the graph locally for nodes/edges matching keywords."""
        G = self._load_graph()
        if G is None:
            return {"error": "Cannot load graph"}

        keywords = [w.lower() for w in question.split() if len(w) > 2]
        matches = []

        for nid, attrs in G.nodes(data=True):
            name_lower = str(nid).lower()
            desc = str(attrs.get("description", "")).lower()
            label = str(attrs.get("label", "")).lower()
            score = sum(1 for k in keywords if k in name_lower or k in desc or k in label)
            if score > 0:
                matches.append({
                    "node": nid,
                    "type": attrs.get("type", "unknown"),
                    "description": attrs.get("description", ""),
                    "community": attrs.get("community", ""),
                    "score": score,
                    "connections": list(G.neighbors(nid))[:10],
                })

        matches.sort(key=lambda x: x["score"], reverse=True)
        return {
            "question": question,
            "matches": matches[:15],
            "total_matches": len(matches),
            "graph_nodes": G.number_of_nodes(),
            "graph_edges": G.number_of_edges(),
        }

    def _explain_local(self, concept: str) -> Dict:
        """Explain a concept by finding its node and neighborhood."""
        G = self._load_graph()
        if G is None:
            return {"error": "Cannot load graph"}

        # Find best matching node
        concept_lower = concept.lower()
        best_node = None
        best_score = 0

        for nid in G.nodes():
            nid_lower = str(nid).lower()
            if concept_lower == nid_lower:
                best_node = nid
                break
            if concept_lower in nid_lower:
                score = len(concept_lower) / len(nid_lower)
                if score > best_score:
                    best_score = score
                    best_node = nid

        if best_node is None:
            return {"error": f"Concept '{concept}' not found in graph"}

        attrs = dict(G.nodes[best_node])
        neighbors = []
        for neighbor in G.neighbors(best_node):
            edge_data = G.edges[best_node, neighbor]
            neighbors.append({
                "node": neighbor,
                "relationship": edge_data.get("type", edge_data.get("relationship", "connected_to")),
                "confidence": edge_data.get("confidence_score", 1.0),
            })

        return {
            "concept": best_node,
            "attributes": attrs,
            "connections": neighbors,
            "degree": G.degree(best_node),
        }

    # ── Agent Context ────────────────────────────────────────────────

    def get_agent_context(self, agent_tag: str, query: str = "") -> str:
        """
        Get graph-derived context for a specific agent.
        Agents can use this to enhance their responses with structural insights.
        """
        if not self.is_built():
            return ""

        # Map agent tags to relevant graph queries
        agent_domains = {
            "[REV]": "revenue sales pricing profit transactions",
            "[OPS]": "operations workflow delivery efficiency orders",
            "[CUS]": "customer loyalty retention churn satisfaction",
            "[INV]": "inventory stock supply ingredients waste",
            "[MKT]": "marketing campaigns promotions social media",
            "[FIN]": "finance cost budget cash flow profit margin",
            "[DAT]": "data patterns trends analysis forecast",
            "[TEC]": "technology api system architecture code",
            "[GRO]": "growth funnel conversion acquisition",
            "[PAR]": "partnership supplier vendor collaboration",
        }

        domain_query = agent_domains.get(agent_tag, "business")
        full_query = f"{domain_query} {query}".strip()

        result = self.query(full_query, budget=500)
        if "error" in result:
            return ""

        if "answer" in result:
            return f"\n[Knowledge Graph Context]\n{result['answer']}\n"

        if "matches" in result and result["matches"]:
            lines = ["[Knowledge Graph Context]"]
            for m in result["matches"][:5]:
                lines.append(f"- {m['node']}: {m.get('description', '')} (connections: {len(m.get('connections', []))})")
            return "\n".join(lines)

        return ""


# ── Singleton ────────────────────────────────────────────────────────

_instance: Optional[MafaliaGraphify] = None


def get_graphify(data_dir: str = ".") -> MafaliaGraphify:
    global _instance
    if _instance is None or str(_instance.data_dir) != str(Path(data_dir).resolve()):
        _instance = MafaliaGraphify(data_dir)
    return _instance
