# -*- coding: utf-8 -*-
"""
Mafalia Agent Skill Definitions
================================
Structured skill catalog for all 10 Mafalia AI agents.
Each skill has an ID, name, description, input schema, and execution logic.
"""

from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional
from enum import Enum


class SkillCategory(Enum):
    ANALYTICS = "analytics"
    STRATEGY = "strategy"
    OPERATIONS = "operations"
    COMMUNICATION = "communication"
    FORECASTING = "forecasting"
    OPTIMIZATION = "optimization"
    MONITORING = "monitoring"
    AUTOMATION = "automation"


@dataclass
class Skill:
    id: str
    name: str
    description: str
    agent: str
    category: SkillCategory
    input_params: List[Dict]
    output_description: str
    difficulty: str
    estimated_time: str
    examples: List[str] = field(default_factory=list)
    requires_data: List[str] = field(default_factory=list)


AGENT_SKILLS: Dict[str, List[Skill]] = {

    # ─────────────────────────────────────────────────────
    # ZARA - Revenue Strategist
    # ─────────────────────────────────────────────────────
    "zara": [
        Skill(
            id="zara_01",
            name="Revenue Analysis",
            description="Deep analysis of total revenue, transaction volume, average order value, best/worst performance days",
            agent="zara",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Revenue totals, transaction count, daily breakdown, best/worst days",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["What is our total revenue?", "How are our sales performing?"],
            requires_data=["transactions_rows.csv"],
        ),
        Skill(
            id="zara_02",
            name="Price Optimization",
            description="Identifies over- and under-priced products based on demand elasticity and sales velocity",
            agent="zara",
            category=SkillCategory.OPTIMIZATION,
            input_params=[],
            output_description="Per-product pricing recommendations with expected revenue impact",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["Optimize our product pricing", "Which items can we price higher?"],
            requires_data=["produits_rows.csv", "produits_commandes_rows.csv"],
        ),
        Skill(
            id="zara_03",
            name="Profit Margin Analysis",
            description="Calculates gross/net profit margins and breaks down costs vs revenue",
            agent="zara",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Profit margins, cost breakdown, net profit",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["What is our profit margin?", "Analyze our profitability"],
            requires_data=["transactions_rows.csv"],
        ),
        Skill(
            id="zara_04",
            name="Upsell Opportunity Detection",
            description="Mines order history to find frequently co-purchased items for bundle/upsell recommendations",
            agent="zara",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Bundle suggestions with frequency data and recommended discount",
            difficulty="medium",
            estimated_time="< 3s",
            examples=["What bundles should we create?", "Find upsell opportunities"],
            requires_data=["produits_commandes_rows.csv", "produits_rows.csv"],
        ),
        Skill(
            id="zara_05",
            name="Revenue Trend Detection",
            description="Identifies weekly/daily revenue trends, volatility, and momentum",
            agent="zara",
            category=SkillCategory.FORECASTING,
            input_params=[],
            output_description="Trend direction, weekly change %, volatility, last/previous period comparison",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["Is revenue going up or down?", "Revenue trends analysis"],
            requires_data=["transactions_rows.csv"],
        ),
        Skill(
            id="zara_06",
            name="POS Analytics",
            description="Restaurant POS (caisse connectée) analytics: transaction volume, payment breakdown, multi-centre stats",
            agent="zara",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="POS transaction count, revenue, payment method breakdown, location stats",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["POS analytics", "How is our caisse performing?", "Analyse du terminal de vente"],
            requires_data=["transactions_rows.csv", "payment_methods_rows.csv", "centre_rows.csv"],
        ),
        Skill(
            id="zara_07",
            name="Retail Revenue Analysis",
            description="Détaillant (retail) revenue analysis: catalog size, average basket, product pricing, growth levers",
            agent="zara",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Retail revenue, avg basket, catalog size, growth recommendations",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Retail revenue analysis", "Analyse détaillant", "Boutique performance"],
            requires_data=["transactions_rows.csv", "produits_rows.csv"],
        ),
    ],

    # ─────────────────────────────────────────────────────
    # KOFI - Operations Commander
    # ─────────────────────────────────────────────────────
    "kofi": [
        Skill(
            id="kofi_01",
            name="Order Flow Analysis",
            description="Analyzes order distribution by type, mode, and status",
            agent="kofi",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Total orders by mode/type/status",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["How are orders distributed?", "Analyze our order flow"],
            requires_data=["commandes_rows.csv"],
        ),
        Skill(
            id="kofi_02",
            name="Bottleneck Detection",
            description="Scans operations data for congestion points: pending orders, failed payments, slow processes",
            agent="kofi",
            category=SkillCategory.MONITORING,
            input_params=[],
            output_description="List of bottlenecks with severity and recommended actions",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["Where are our operational bottlenecks?", "What's slowing us down?"],
            requires_data=["commandes_rows.csv", "transactions_rows.csv"],
        ),
        Skill(
            id="kofi_03",
            name="Efficiency Scoring",
            description="Scores operational efficiency across 5 dimensions: orders, payments, inventory, service, delivery",
            agent="kofi",
            category=SkillCategory.MONITORING,
            input_params=[],
            output_description="Overall score /100 per category, top performer, needs improvement",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["What is our efficiency score?", "Score our operations"],
            requires_data=[],
        ),
        Skill(
            id="kofi_04",
            name="Delivery Analysis",
            description="Analyzes delivery vs pickup vs dine-in distribution and ratios",
            agent="kofi",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Order count by fulfillment mode with percentages",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["How many delivery orders do we have?", "Delivery vs dine-in breakdown"],
            requires_data=["commandes_rows.csv"],
        ),
        Skill(
            id="kofi_05",
            name="Staff Analysis",
            description="Reviews staffing data: headcount by role and recommendations",
            agent="kofi",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Staff count by role and scheduling recommendations",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Analyze our staff", "How is our team structured?"],
            requires_data=["informations_employees_rows.csv"],
        ),
        Skill(
            id="kofi_06",
            name="Hotel PMS Management",
            description="Hotel PMS intelligence: reservations, front desk, room management, guest services, tarification dynamique",
            agent="kofi",
            category=SkillCategory.OPERATIONS,
            input_params=[],
            output_description="PMS modules, KPIs (RevPAR, ADR, taux d'occupation), integrations, recommendations",
            difficulty="medium",
            estimated_time="< 1s",
            examples=["Hotel PMS overview", "Gestion hôtelière", "Room management", "Taux d'occupation"],
            requires_data=[],
        ),
        Skill(
            id="kofi_07",
            name="Housekeeping Orchestration",
            description="Ménage & maintenance en temps réel: task assignment, room status cycle, SLAs, inspection tracking",
            agent="kofi",
            category=SkillCategory.OPERATIONS,
            input_params=[],
            output_description="Workflow, KPIs (cleaning time, rooms/attendant, inspection rate), features, recommendations",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Housekeeping status", "Ménage des chambres", "Maintenance report"],
            requires_data=[],
        ),
        Skill(
            id="kofi_08",
            name="Transport & Logistics",
            description="Logistique fournisseurs connectée: fleet management, supplier logistics, delivery dispatch",
            agent="kofi",
            category=SkillCategory.OPERATIONS,
            input_params=[],
            output_description="Fleet management, supplier logistics, delivery dispatch features and KPIs",
            difficulty="medium",
            estimated_time="< 1s",
            examples=["Transport logistics", "Suivi des véhicules", "Gestion de la flotte", "Delivery dispatch"],
            requires_data=[],
        ),
    ],

    # ─────────────────────────────────────────────────────
    # AMARA - Customer Champion
    # ─────────────────────────────────────────────────────
    "amara": [
        Skill(
            id="amara_01",
            name="Customer Overview",
            description="Total customers, active vs inactive, average orders, top spenders",
            agent="amara",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Customer counts, activity rates, top 5 customers",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Who are our customers?", "Customer overview"],
            requires_data=["clients_rows.csv"],
        ),
        Skill(
            id="amara_02",
            name="Churn Prediction",
            description="Identifies at-risk customers based on order frequency and engagement patterns",
            agent="amara",
            category=SkillCategory.FORECASTING,
            input_params=[],
            output_description="At-risk customer list with risk level and recommended action",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["Who is about to churn?", "Identify at-risk customers"],
            requires_data=["clients_rows.csv"],
        ),
        Skill(
            id="amara_03",
            name="Loyalty Analysis",
            description="Analyzes loyalty point distribution across Bronze/Silver/Gold/VIP tiers",
            agent="amara",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Points issued, avg per customer, tier distribution, engagement rate",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Loyalty program performance", "How are loyalty tiers distributed?"],
            requires_data=["clients_rows.csv"],
        ),
        Skill(
            id="amara_04",
            name="Customer Segmentation",
            description="Segments customers into VIP, New, Regular, and Loyal with tailored strategies",
            agent="amara",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Customer counts per segment with engagement strategy for each",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["Segment our customers", "Customer segmentation analysis"],
            requires_data=["clients_rows.csv"],
        ),
        Skill(
            id="amara_05",
            name="Customer Lifetime Value",
            description="Calculates average, median, max, and total CLV across all customers",
            agent="amara",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="CLV stats: average, median, max, total portfolio value",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["What is our customer lifetime value?", "Calculate CLV"],
            requires_data=["clients_rows.csv"],
        ),
    ],

    # ─────────────────────────────────────────────────────
    # IDRIS - Inventory Guardian
    # ─────────────────────────────────────────────────────
    "idris": [
        Skill(
            id="idris_01",
            name="Stock Level Check",
            description="Real-time stock status for all products: critical/low/normal classification",
            agent="idris",
            category=SkillCategory.MONITORING,
            input_params=[],
            output_description="Item count by status, critical items list",
            difficulty="easy",
            estimated_time="< 2s",
            examples=["What's our stock status?", "Check inventory levels"],
            requires_data=["entrees_stock_rows.csv", "sorties_stock_rows.csv"],
        ),
        Skill(
            id="idris_02",
            name="Auto-Reorder Suggestions",
            description="Generates purchase orders for items below safe threshold with priority and estimated cost",
            agent="idris",
            category=SkillCategory.AUTOMATION,
            input_params=[],
            output_description="Purchase orders list with quantity, priority, estimated cost",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["What do we need to reorder?", "Generate purchase orders"],
            requires_data=["entrees_stock_rows.csv", "sorties_stock_rows.csv"],
        ),
        Skill(
            id="idris_03",
            name="Waste Analysis",
            description="Calculates waste % by comparing stock-in vs stock-out and provides reduction recommendations",
            agent="idris",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Total received/used, waste %, reduction recommendations",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["How much are we wasting?", "Analyze food waste"],
            requires_data=["entrees_stock_rows.csv", "sorties_stock_rows.csv"],
        ),
        Skill(
            id="idris_04",
            name="Expiry Tracking",
            description="Flags items expiring within 7 days and those already expired",
            agent="idris",
            category=SkillCategory.MONITORING,
            input_params=[],
            output_description="Expiring items list with product name, quantity, date",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["What items are expiring soon?", "Expiry date check"],
            requires_data=["entrees_stock_rows.csv"],
        ),
        Skill(
            id="idris_05",
            name="Supplier Scorecard",
            description="Scores suppliers by volume, pricing, and reliability",
            agent="idris",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Supplier performance table",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["Rate our suppliers", "Supplier performance analysis"],
            requires_data=["entrees_stock_rows.csv"],
        ),
        Skill(
            id="idris_06",
            name="Fournisseurs & Supply Chain",
            description="Gestion fournisseurs complète: répertoire, bons de commande auto, scoring fournisseurs, comparaison prix, Marketplace Mafalia",
            agent="idris",
            category=SkillCategory.OPERATIONS,
            input_params=[],
            output_description="Supplier directory, purchase orders, scoring criteria, price comparison, Marketplace features",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["Gestion fournisseurs", "Supply chain overview", "Marketplace Mafalia", "Comparer les fournisseurs"],
            requires_data=["entrees_stock_rows.csv"],
        ),
    ],

    # ─────────────────────────────────────────────────────
    # NALA - Marketing Maven
    # ─────────────────────────────────────────────────────
    "nala": [
        Skill(
            id="nala_01",
            name="Campaign Ideas Generator",
            description="Generates 5 ready-to-launch marketing campaigns with channels, targets, and expected impact",
            agent="nala",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="5 campaign ideas with full details",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Give me marketing campaign ideas", "What campaigns should we run?"],
            requires_data=[],
        ),
        Skill(
            id="nala_02",
            name="Social Media Strategy",
            description="Platform-specific social media strategy for WhatsApp, Instagram, TikTok",
            agent="nala",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Per-platform strategy with frequency, timing, content types",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Social media strategy", "How to use WhatsApp for marketing?"],
            requires_data=[],
        ),
        Skill(
            id="nala_03",
            name="Promotion Analysis",
            description="Analyzes current promotions and recommends optimization strategies",
            agent="nala",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Active promos count, types, optimization recommendations",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["Analyze our promotions", "How effective are our promos?"],
            requires_data=["promotions_rows.csv"],
        ),
        Skill(
            id="nala_04",
            name="Content Calendar Builder",
            description="Builds a 7-day content calendar with themes and content types per day",
            agent="nala",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Daily content plan for the week",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Build a content calendar", "What to post each day this week?"],
            requires_data=[],
        ),
        Skill(
            id="nala_05",
            name="Campaign ROI Tracker",
            description="Defines metrics and benchmarks to track marketing ROI across channels",
            agent="nala",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Metrics to track, benchmark targets per channel",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["How do I measure campaign ROI?", "Marketing metrics"],
            requires_data=[],
        ),
    ],

    # ─────────────────────────────────────────────────────
    # TARIQ - Finance Wizard
    # ─────────────────────────────────────────────────────
    "tariq": [
        Skill(
            id="tariq_01",
            name="Cash Flow Analysis",
            description="Daily, weekly, and monthly cash flow projections based on transaction history",
            agent="tariq",
            category=SkillCategory.FORECASTING,
            input_params=[],
            output_description="Daily average, weekly/monthly projections, week-over-week change",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["What is our cash flow?", "Project our revenue this month"],
            requires_data=["transactions_rows.csv"],
        ),
        Skill(
            id="tariq_02",
            name="Financial Health Score",
            description="Scores financial health across 5 dimensions with overall rating",
            agent="tariq",
            category=SkillCategory.MONITORING,
            input_params=[],
            output_description="Overall score, category breakdown, rating (Good/Needs Improvement/Critical)",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Financial health check", "What is our financial health score?"],
            requires_data=["transactions_rows.csv"],
        ),
        Skill(
            id="tariq_03",
            name="Budget Planning",
            description="Recommends budget allocation percentages for all cost categories",
            agent="tariq",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Budget allocation by category as % and FCFA amounts",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Help plan our budget", "Budget allocation recommendations"],
            requires_data=["transactions_rows.csv"],
        ),
        Skill(
            id="tariq_04",
            name="Tax Insights (Senegal)",
            description="Overview of Senegal tax obligations, deductions, and optimization tips for restaurants",
            agent="tariq",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Tax rates, deductions available, compliance recommendations",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Tax obligations in Senegal", "How to optimize our taxes?"],
            requires_data=[],
        ),
        Skill(
            id="tariq_05",
            name="Investment Analysis",
            description="Ranks investment priorities by ROI potential and recommends funding options",
            agent="tariq",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Investment priorities ranked with ROI estimates and funding options",
            difficulty="medium",
            estimated_time="< 1s",
            examples=["Where should we invest?", "Investment priorities"],
            requires_data=[],
        ),
        Skill(
            id="tariq_06",
            name="Credit Scoring IA",
            description="AI-powered credit scoring based on Mafalia transaction data: score factors, eligible financing, improvement tips",
            agent="tariq",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Credit score /100, rating, score factors, eligible financing types, improvement actions",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["What is my credit score?", "Accès au financement", "Credit scoring", "Suis-je éligible au prêt?"],
            requires_data=["transactions_rows.csv", "clients_rows.csv"],
        ),
        Skill(
            id="tariq_07",
            name="Payment Gateway (API Paiement)",
            description="Multi-channel payment gateway: supported methods (Wave, Orange Money, Visa), API features, integration guide",
            agent="tariq",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Supported payment methods, API features, payment distribution, integration steps",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Payment methods overview", "API Paiement", "Configurer les paiements", "Wave integration"],
            requires_data=["transactions_rows.csv", "payment_methods_rows.csv"],
        ),
        Skill(
            id="tariq_08",
            name="Carte Mafalia (Salary Cards)",
            description="Employee salary card management: Visa prepaid, MassPay instant payroll, expense tracking, advance management",
            agent="tariq",
            category=SkillCategory.OPERATIONS,
            input_params=[],
            output_description="Card features, employer/employee benefits, employee count, payroll integration",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Carte salaire", "Carte Mafalia", "MassPay", "Payer les salaires"],
            requires_data=["informations_employees_rows.csv"],
        ),
        Skill(
            id="tariq_09",
            name="Comptabilité Automatisée",
            description="Automated accounting: journal entries from POS, invoicing, bank reconciliation, SYSCOHADA compliance, tax reporting",
            agent="tariq",
            category=SkillCategory.AUTOMATION,
            input_params=[],
            output_description="Accounting modules, automation rules, reports, Senegal compliance (SYSCOHADA, DGID, NINEA)",
            difficulty="medium",
            estimated_time="< 1s",
            examples=["Comptabilité overview", "Automated accounting", "Bilan financier", "Déclaration TVA"],
            requires_data=["transactions_rows.csv"],
        ),
    ],

    # ─────────────────────────────────────────────────────
    # SANA - Data Scientist
    # ─────────────────────────────────────────────────────
    "sana": [
        Skill(
            id="sana_01",
            name="Sales Forecasting",
            description="7-day sales forecast using trend-based linear modeling with confidence intervals",
            agent="sana",
            category=SkillCategory.FORECASTING,
            input_params=[],
            output_description="Day-by-day predictions with confidence intervals",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["Forecast next 7 days sales", "Sales predictions"],
            requires_data=["transactions_rows.csv"],
        ),
        Skill(
            id="sana_02",
            name="Pattern Recognition",
            description="Identifies peak hours, peak days, and order mode patterns in transaction data",
            agent="sana",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Peak hours, peak days, behavioral patterns",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["Find patterns in our data", "When are peak hours?"],
            requires_data=["transactions_rows.csv", "commandes_rows.csv"],
        ),
        Skill(
            id="sana_03",
            name="Anomaly Detection",
            description="Detects statistical anomalies in transaction amounts using z-score method (2σ threshold)",
            agent="sana",
            category=SkillCategory.MONITORING,
            input_params=[],
            output_description="High/low anomaly counts with top unusual transactions",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["Detect anomalies in transactions", "Unusual transactions"],
            requires_data=["transactions_rows.csv"],
        ),
        Skill(
            id="sana_04",
            name="Correlation Analysis",
            description="Identifies key business variable correlations with actionable insights",
            agent="sana",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Correlation pairs with strength and business insight",
            difficulty="medium",
            estimated_time="< 1s",
            examples=["What correlates with sales?", "Find correlations in our data"],
            requires_data=[],
        ),
        Skill(
            id="sana_05",
            name="Key Insights Extraction",
            description="Synthesizes all data into 5-10 actionable business insights",
            agent="sana",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Key insights list with data quality assessment",
            difficulty="easy",
            estimated_time="< 2s",
            examples=["Give me key insights", "What does our data tell us?"],
            requires_data=["transactions_rows.csv", "clients_rows.csv"],
        ),
        Skill(
            id="sana_06",
            name="Carbone Mesure",
            description="Environmental impact tracking: carbon footprint from delivery, supply chain, and energy; reduction actions; RSE/ESG reporting",
            agent="sana",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Carbon footprint (kg CO2), breakdown by source, benchmarks, reduction actions, reporting options",
            difficulty="medium",
            estimated_time="< 2s",
            examples=["Empreinte carbone", "Carbon footprint", "Impact environnemental", "Rapport RSE"],
            requires_data=["transactions_rows.csv", "commandes_rows.csv", "entrees_stock_rows.csv"],
        ),
    ],

    # ─────────────────────────────────────────────────────
    # RAVI - Tech Architect
    # ─────────────────────────────────────────────────────
    "ravi": [
        Skill(
            id="ravi_01",
            name="API Recommendations",
            description="Lists all Mafalia API endpoints with purpose and integration tips",
            agent="ravi",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="API endpoints list with integration best practices",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["What APIs are available?", "How to integrate with Mafalia?"],
            requires_data=[],
        ),
        Skill(
            id="ravi_02",
            name="Security Audit",
            description="Comprehensive security checklist with priority ratings and compliance requirements",
            agent="ravi",
            category=SkillCategory.MONITORING,
            input_params=[],
            output_description="Security checklist with status, priority, compliance notes",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Security audit", "How secure is our system?"],
            requires_data=[],
        ),
        Skill(
            id="ravi_03",
            name="Performance Optimization",
            description="Performance tips for database, application, and infrastructure layers",
            agent="ravi",
            category=SkillCategory.OPTIMIZATION,
            input_params=[],
            output_description="Optimization tips by layer",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["How to improve performance?", "System performance tips"],
            requires_data=[],
        ),
        Skill(
            id="ravi_04",
            name="Tech Stack Advisory",
            description="Recommended technology stack and mapping to Mafalia's current tech",
            agent="ravi",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Recommended stack + Mafalia current stack",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["What tech stack should we use?", "Technology recommendations"],
            requires_data=[],
        ),
        Skill(
            id="ravi_05",
            name="Automation Opportunities",
            description="High-ROI automation opportunities ranked by complexity and impact",
            agent="ravi",
            category=SkillCategory.AUTOMATION,
            input_params=[],
            output_description="Automation ideas with impact and complexity ratings",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["What can we automate?", "Automation opportunities"],
            requires_data=[],
        ),
        Skill(
            id="ravi_06",
            name="PMS API Integration",
            description="Hotel PMS API: reservations, guest, room, billing, reporting modules; channel manager; SDK & webhook integration",
            agent="ravi",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="API modules with endpoints, channel manager platforms, integration options",
            difficulty="medium",
            estimated_time="< 1s",
            examples=["PMS API documentation", "Hotel API integration", "Channel manager setup"],
            requires_data=[],
        ),
        Skill(
            id="ravi_07",
            name="Téléphone Mafalia POS",
            description="POS préinstallé, prêt à l'emploi: Android smartphone with Mafalia app, specs, included software, use cases",
            agent="ravi",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Phone specs, included software, ideal use cases, pricing info",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Téléphone POS", "Phone POS specs", "Mafalia phone"],
            requires_data=[],
        ),
        Skill(
            id="ravi_08",
            name="Terminaux POS",
            description="Caisses tactiles certifiées: Terminal Pro, Terminal Compact, TPE with PCI DSS/EMV/GIM-UEMOA certifications",
            agent="ravi",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Terminal models with specs, features, certifications, ideal use cases",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["POS terminals", "Terminaux de caisse", "Quel terminal choisir?"],
            requires_data=[],
        ),
        Skill(
            id="ravi_09",
            name="Tablettes & Kiosques",
            description="Bornes de commande & accueil: kiosque libre-service, tablette serveur, kiosque d'accueil hôtel",
            agent="ravi",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Kiosk/tablet products with specs, features, upselling impact",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Bornes de commande", "Tablettes serveur", "Kiosque d'accueil"],
            requires_data=[],
        ),
        Skill(
            id="ravi_10",
            name="Imprimantes",
            description="Tickets, reçus, étiquettes: thermique reçus, imprimante cuisine, imprimante d'étiquettes",
            agent="ravi",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Printer models with specs, connectivity, use cases",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Imprimantes disponibles", "Imprimante cuisine", "Imprimante étiquettes"],
            requires_data=[],
        ),
        Skill(
            id="ravi_11",
            name="Equipment Overview",
            description="Vue d'ensemble de tous les équipements Mafalia: téléphone, terminaux, tablettes, kiosques, imprimantes avec support",
            agent="ravi",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Full equipment catalog with support options (installation, formation, maintenance, hotline)",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Équipements Mafalia", "Hardware catalog", "Quel matériel choisir?"],
            requires_data=[],
        ),
    ],

    # ─────────────────────────────────────────────────────
    # LUNA - Growth Hacker
    # ─────────────────────────────────────────────────────
    "luna": [
        Skill(
            id="luna_01",
            name="Growth Strategy Design",
            description="Quick wins, medium-term, and long-term growth strategies ranked by effort/impact",
            agent="luna",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Growth strategies in 3 horizons: quick wins, medium, long-term",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Growth strategy", "How do we grow?"],
            requires_data=[],
        ),
        Skill(
            id="luna_02",
            name="Funnel Analysis",
            description="Analyzes conversion funnel from awareness to retention with optimization tips",
            agent="luna",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Funnel stages with rates and optimization recommendations",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Analyze our funnel", "Conversion funnel analysis"],
            requires_data=[],
        ),
        Skill(
            id="luna_03",
            name="Experiment Design",
            description="Designs A/B tests and experiments with hypothesis, metrics, duration, and sample size",
            agent="luna",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="3 experiment designs ready to run",
            difficulty="medium",
            estimated_time="< 1s",
            examples=["Design A/B tests", "What experiments should we run?"],
            requires_data=[],
        ),
        Skill(
            id="luna_04",
            name="Viral Mechanics Design",
            description="Designs referral programs, social sharing triggers, and UGC campaigns",
            agent="luna",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Referral program structure, sharing mechanics, UGC campaign",
            difficulty="medium",
            estimated_time="< 1s",
            examples=["Referral program design", "How to make our business viral?"],
            requires_data=[],
        ),
        Skill(
            id="luna_05",
            name="Retention Strategy",
            description="Win-back, milestone, exclusive, and feedback loop retention strategies",
            agent="luna",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="4 retention strategies with target, action, and expected result",
            difficulty="medium",
            estimated_time="< 1s",
            examples=["How to retain customers?", "Retention strategy"],
            requires_data=[],
        ),
    ],

    # ─────────────────────────────────────────────────────
    # OMAR - Partnership Connector
    # ─────────────────────────────────────────────────────
    "omar": [
        Skill(
            id="omar_01",
            name="Partnership Opportunities",
            description="Maps 4 partnership types (cross-promo, delivery, supplier, payment) with Mafalia partner list",
            agent="omar",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Partnership types, benefits, and current Mafalia partners",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Partnership opportunities", "Who should we partner with?"],
            requires_data=[],
        ),
        Skill(
            id="omar_02",
            name="Supplier Matching",
            description="Connects to Mafalia Marketplace for direct supplier sourcing with 50% savings potential",
            agent="omar",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Marketplace benefits, categories, sourcing recommendation",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Find suppliers", "Mafalia marketplace suppliers"],
            requires_data=[],
        ),
        Skill(
            id="omar_03",
            name="Deal Structuring",
            description="Negotiation tips and deal structure templates (volume, long-term, exclusive)",
            agent="omar",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Negotiation tips and 3 deal structure types with typical savings",
            difficulty="medium",
            estimated_time="< 1s",
            examples=["How to negotiate better deals?", "Deal structuring advice"],
            requires_data=[],
        ),
        Skill(
            id="omar_04",
            name="Ecosystem Mapping",
            description="Maps the full Mafalia ecosystem: core platform, financial, marketing, operational services",
            agent="omar",
            category=SkillCategory.ANALYTICS,
            input_params=[],
            output_description="Full ecosystem map with integration opportunities",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Map the Mafalia ecosystem", "What does Mafalia offer?"],
            requires_data=[],
        ),
        Skill(
            id="omar_05",
            name="Financing Options",
            description="Guides through Mafalia financing options (BFR, LendIA) and alternative funding sources",
            agent="omar",
            category=SkillCategory.STRATEGY,
            input_params=[],
            output_description="Mafalia financing products, other options, recommendation",
            difficulty="easy",
            estimated_time="< 1s",
            examples=["Financing options", "How to get business financing?"],
            requires_data=[],
        ),
    ],
}


def get_skills_for_agent(agent_name: str) -> List[Skill]:
    return AGENT_SKILLS.get(agent_name.lower(), [])


def get_all_skills() -> Dict[str, List[Dict]]:
    result = {}
    for agent_name, skills in AGENT_SKILLS.items():
        result[agent_name] = [
            {
                "id": s.id,
                "name": s.name,
                "description": s.description,
                "category": s.category.value,
                "difficulty": s.difficulty,
                "estimated_time": s.estimated_time,
                "examples": s.examples,
                "requires_data": s.requires_data,
            }
            for s in skills
        ]
    return result


def get_skill_by_id(skill_id: str) -> Optional[Dict]:
    for agent_name, skills in AGENT_SKILLS.items():
        for skill in skills:
            if skill.id == skill_id:
                return {
                    "id": skill.id,
                    "name": skill.name,
                    "description": skill.description,
                    "agent": skill.agent,
                    "category": skill.category.value,
                    "difficulty": skill.difficulty,
                    "estimated_time": skill.estimated_time,
                    "examples": skill.examples,
                    "requires_data": skill.requires_data,
                    "output_description": skill.output_description,
                }
    return None


def get_skills_by_category(category: str) -> List[Dict]:
    results = []
    for agent_name, skills in AGENT_SKILLS.items():
        for skill in skills:
            if skill.category.value == category:
                results.append({
                    "id": skill.id,
                    "name": skill.name,
                    "agent": agent_name,
                    "category": category,
                    "difficulty": skill.difficulty,
                })
    return results


def skills_summary() -> Dict:
    total = sum(len(s) for s in AGENT_SKILLS.values())
    by_category = {}
    by_difficulty = {}
    for agent_name, skills in AGENT_SKILLS.items():
        for skill in skills:
            cat = skill.category.value
            diff = skill.difficulty
            by_category[cat] = by_category.get(cat, 0) + 1
            by_difficulty[diff] = by_difficulty.get(diff, 0) + 1
    return {
        "total_skills": total,
        "agents": len(AGENT_SKILLS),
        "skills_per_agent": {name: len(skills) for name, skills in AGENT_SKILLS.items()},
        "by_category": by_category,
        "by_difficulty": by_difficulty,
    }
